name: Code Coverage
on:
    pull_request:
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install modules
        run: yarn install

      - uses: ArtiomTr/jest-coverage-report-action@v2  
        with:
          test-script: npm test
          threshold: 80
  
        
